const users = [
  {
    name: 'Marta Sanz Buezo',
    username: 'marsabue',
    avatar: 'assets/img/avatars/marta.svg',
    apps: [1, 2, 3, 4, 5],
  },
  {
    name: 'Rafael Martínez Amor',
    username: 'ramara',
    avatar: 'assets/img/avatars/rafael.svg',
    apps: [1, 2, 3, 4, 5],
  },
  {
    name: 'Isabel Díez',
    username: 'isadi',
    avatar: 'assets/img/avatars/isabel.svg',
    apps: [1, 2, 3, 4, 5],
  },
  {
    name: 'Dominique Tiendrebeogo',
    username: 'doti',
    avatar: 'assets/img/avatars/dominique.svg',
    apps: [1, 2, 3, 4, 5],
  },
  {
    name: 'Fiorina Facio',
    username: 'fiofa',
    avatar: 'assets/img/avatars/fiorina.svg',
    apps: [1, 2, 3, 4, 5],
  },
  {
    name: 'Belén Santamaría',
    username: 'besan',
    avatar: 'assets/img/avatars/belen.svg',
    apps: [1, 2, 3, 4, 5],
  },
  {
    name: 'Socio Semanal',
    username: 'semanal',
    avatar: 'assets/img/avatars/semanal.svg',
    apps: [6, 13, 10, 12, 7],
  },
  {
    name: 'Socio Quincenal 1',
    username: 'uno',
    avatar: 'assets/img/avatars/quincena-1.svg',
    apps: [8, 13, 10, 12, 7],
  },
  {
    name: ' Socio Quincenal 2 ',
    username: 'dos',
    avatar: 'assets/img/avatars/quincena-2.svg',
    apps: [9, 13, 10, 12, 7],
  },
];

const apps = [
  {
    id: 1,
    url: 'https://docs.google.com/forms/d/1OrfWGGCM3vkWGYVqzYkPsCVS5c_Gl8iXEUL5cUhcCPA/edit?usp=sharing',
    icon: 'bi-stopwatch',
    title: 'Jornada',
    description: 'Registro de entradas y salidas',
  },
  {
    id: 2,
    url: 'https://drive.google.com/drive/folders/14ad7Qxbx8YBxDmvrqUMEumWjD_bcLjeK?usp=sharing',
    icon: 'bi-pencil',
    title: 'Fichajes',
    description: 'Revisión de entradas y salidas',
  },
  {
    id: 3,
    url: 'https://docs.google.com/forms/d/1jJ8WUmKxGeQwGpn-QEZgkCE1mNnTMRvf1xV6glR79xo/edit?usp=sharing',
    icon: 'bi-rainbow',
    title: 'Campo',
    description: 'Registro de prácticas',
  },
  {
    id: 4,
    url: 'https://docs.google.com/forms/d/16IBZ9W20Ki7-l1GmrLjMg_2KlxldjieknhYht4Xru7s/edit?usp=sharing',
    icon: 'bi-people-fill',
    title: 'Socios',
    description: 'Nuevos Interesados',
  },
  {
    id: 5,
    url: 'https://docs.google.com/spreadsheets/d/1UXvhccl5f9JhhtyuH7kJem_BBU_tLSiDjFImvpewlxQ/edit?usp=sharing',
    icon: 'bi-cloud-sun',
    title: 'Vacaciones',
    description: 'Registro común',
  },
  {
    id: 6,
    url: 'https://drive.google.com/file/d/1ir5amnJ3xqipmKWcH9AfvRlgXIz76x3J/view?usp=sharing',
    icon: 'bi-calendar-date',
    title: 'Calendario',
    description: 'Recogida cesta semanal',
  },
  {
    id: 8,
    url: 'https://drive.google.com/file/d/1yOzwc39OcqRqZnMJSfDA99IkSgAS4_F7/view?usp=sharing',
    icon: 'bi-calendar-minus',
    title: 'Calendario',
    description: 'Recogida cesta quincenal',
  },
  {
    id: 9,
    url: 'https://drive.google.com/file/d/1kTVSGinBVhm6SL9ddnQIML5BDA0qrzGy/view?usp=sharing',
    icon: 'bi-calendar-plus',
    title: 'Calendario',
    description: 'Recogida cesta quincenal',
  },
  {
    id: 13,
    url: 'https://docs.google.com/spreadsheets/d/1yGqipycrYdAqVgNvuRoYrz2QJJ1dgSeusuls3qgDUcw/edit?usp=sharing',
    icon: 'bi-basket',
    title: 'Ofertas y Productos',
    description: 'Disponible esta semana',
  },
  {
    id: 10,
    url: 'https://docs.google.com/forms/d/14tLUebqpcuuL-bDRVhciQu0fr9ToikQgFt-6pUOW_eM/edit?usp=sharing',
    icon: 'bi-bag-check',
    title: 'Pedido Pan',
    description: 'Enviar antes del domingo a las 24h',
  },
  {
    id: 11,
    url: 'https://docs.google.com/forms/d/12rYogbhmIxs_oYvZTQYVFXYHfsbUFkb9-oElIRQuneI/edit?usp=sharing',
    icon: 'bi-award',
    title: 'Pedido Repostería',
    description: 'Enviar antes del lunes a las 24h',
  },
  {
    id: 12,
    url: 'https://docs.google.com/forms/d/1TC44hksJ4I2QGBwVrGu-cHdGOEkzw_tbq6EBCghGk4U/edit?usp=sharing',
    icon: 'bi-asterisk',
    title: 'Pedido Pollo',
    description: 'Enviar antes del jueves a las 24h',
  },
  {
    id: 7,
    url: 'https://drive.google.com/file/d/1nsZW8izSb1_RaLXIip7saBr9x4pcHed2/view?usp=sharing',
    icon: 'bi-bookmarks',
    title: 'Recetas',
    description: 'Disfruta cocinando nuestros productos',
  },
];
